### ISSUE TITLE
add student school board in application

### ISSUE THREAD

**Issue by aayushi-droid** [aayushi-droid/REST-API#3]
- [x]  add school board category for school 

Like Delhi public school is part of `Central board secondary education`

Before working on issue please comment for isssue assign.

This repository is vaild for HacktoberFest2020
Good Luck,

**Comment by Abhishek723** [comment]
Hey, @aayushi-droid I want to contribute to this issue.

**Comment by ishan-chaudhary** [comment]
Hey , Please assign this issue to me

**Comment by aayushi-droid** [comment]
- [✓] Task Assigned

@Abhishek723

**Comment by aayushi-droid** [comment]
@ishan-chaudhary you can check other repository in Py-droid, There are lot of open issues.

**Comment by aayushi-droid** [comment]
- [x] Task Complete
